import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
import seaborn as sns
import matplotlib.pyplot as plt
from pathlib import Path

MODELS = {
    "openai": "gpt-4.1-mini",
    "anthropic": "claude-haiku-4-5-20251001",
    "google": "gemini-2.5-flash",
	"openrouter": "meta-llama/llama-3.3-70b-instruct",
    "tencent": "hy3", 
    "minimax": "MiniMax-M3",
    "deepseek": "deepseek-v4-pro",
    "qwen": "qwen3.7-plus",
    "mistral": "mistral-medium-latest",
    "sealion": "aisingapore/Gemma-SEA-LION-v4-27B-IT"
}

OUTCOMES = [
	"Hireability_Score",
	"Competence_Score",
	"Fit_Score",
	"Performance_Score",
	"Leadership_Avg",
	"Status_Score",
	"Warmth_Score"
]

def create_step2a_summary(OUTPUT_PATH):

    regression_df = pd.read_csv(OUTPUT_PATH / "step_2a_regression_results.csv")

    # Exact interaction term generated by:
    #
    # C(CV_framing) * C(Seniority_level)
    #
    # Statsmodels should produce:
    #
    # C(CV_framing)[T.Communal]:C(Seniority_level)[T.Senior-Level]
    #
    interaction_term = (
        "C(CV_framing)[T.Communal]:"
        "C(Seniority_level)[T.Senior-Level]"
    )

    summary_df = regression_df[
        regression_df["Term"] == interaction_term
    ].copy()

    # Check that we actually got the expected 70 tests
    expected_tests = 10 * 7

    print("\nStep 2A interaction summary")
    print("--------------------------------")
    print(f"Interaction rows found: {len(summary_df)}")
    print(f"Expected rows: {expected_tests}")

    if len(summary_df) != expected_tests:
        print(
            "WARNING: Number of interaction rows does not match "
            "the expected 70."
        )

    # Add an easy-to-read significance column
    summary_df["Significant_Alpha_0.05"] = (
        summary_df["P_Value"] < 0.05
    )

    # Add direction of interaction
    summary_df["Interaction_Direction"] = summary_df[
        "Coefficient"
    ].apply(
        lambda x: "Positive" if x > 0
        else "Negative" if x < 0
        else "Zero"
    )

    # Keep the most useful columns for the summary
    summary_df = summary_df[
        [
            "Analysis_Step",
            "Model_Provider",
            "Model_Name",
            "Outcome",
            "Prompt_Version",
            "N",
            "R_Squared",
            "Term",
            "Coefficient",
            "Std_Error",
            "T_statistic",
            "P_Value",
            "CI_Lower",
            "CI_Upper",
            "Significant_Alpha_0.05",
            "Interaction_Direction",
        ]
    ]

    # Sort so models/outcomes are easy to inspect
    summary_df = summary_df.sort_values(
        ["Model_Provider", "Outcome"]
    ).reset_index(drop=True)

    # Create output directory if necessary
    OUTPUT_PATH.mkdir(parents=True, exist_ok=True)

    summary_df.to_csv(
        OUTPUT_PATH / "step_2a_summary.csv",
        index=False
    )

    print(f"Summary saved to: {OUTPUT_PATH / "step_2a_summary.csv"}")

    return summary_df

def create_step2a_plots(OUTPUT_PATH):

    descriptive_df = pd.read_csv(OUTPUT_PATH / "step_2a_descriptive_results.csv")

    # Get all model/outcome combinations
    combinations = descriptive_df[
        ["Model_Provider", "Model_Name", "Outcome"]
    ].drop_duplicates()

    plot_count = 0

    for _, combination in combinations.iterrows():

        model_provider = combination["Model_Provider"]
        model_name = combination["Model_Name"]
        outcome = combination["Outcome"]

        # Filter this particular model + outcome
        plot_df = descriptive_df[
            (descriptive_df["Model_Provider"] == model_provider)
            & (descriptive_df["Outcome"] == outcome)
        ].copy()

        # ----------------------------------------------------
        # Make sure the two CV framings and seniority levels
        # are in a predictable order
        # ----------------------------------------------------

        framing_order = [
            "Agentic",
            "Communal"
        ]

        seniority_order = [
            "Entry-Level",
            "Senior-Level"
        ]

        # Some datasets may use slightly different capitalization.
        # This doesn't change the actual values; it simply checks
        # what is available.
        available_framings = [
            x for x in framing_order
            if x in plot_df["CV_framing"].unique()
        ]

        available_seniority = [
            x for x in seniority_order
            if x in plot_df["Seniority_level"].unique()
        ]

        # ----------------------------------------------------
        # Plot
        # ----------------------------------------------------

        fig, ax = plt.subplots(figsize=(8, 6))

        for framing in available_framings:

            framing_df = plot_df[
                plot_df["CV_framing"] == framing
            ].copy()

            # Make sure points appear in Entry -> Senior order
            framing_df["Seniority_order"] = pd.Categorical(
                framing_df["Seniority_level"],
                categories=seniority_order,
                ordered=True
            )

            framing_df = framing_df.sort_values(
                "Seniority_order"
            )

            ax.plot(
                framing_df["Seniority_level"],
                framing_df["Mean"],
                marker="o",
                linewidth=2,
                label=framing
            )

        ax.set_title(
            f"{model_name} — {outcome}"
        )

        ax.set_xlabel(
            "Seniority Level"
        )

        ax.set_ylabel(
            f"Mean {outcome} Score"
        )

        ax.legend(
            title="CV Framing"
        )

        ax.grid(
            True,
            alpha=0.3
        )

        plt.tight_layout()

        # ----------------------------------------------------
        # Safe filename
        # ----------------------------------------------------

        safe_provider = (
            str(model_provider)
            .replace(" ", "_")
            .replace("/", "_")
            .replace("\\", "_")
        )

        safe_outcome = (
            str(outcome)
            .replace(" ", "_")
            .replace("/", "_")
            .replace("\\", "_")
        )

        filename = (
            f"{safe_provider}_{safe_outcome}.png"
        )

        output_path = OUTPUT_PATH / filename

        plt.savefig(
            output_path,
            dpi=300,
            bbox_inches="tight"
        )

        plt.close()

        plot_count += 1

    print("\nStep 2A plots")
    print("--------------------------------")
    print(f"Plots generated: {plot_count}")
    print(f"Plots saved to: {OUTPUT_PATH}")

def main():
	base_dir = Path.cwd()
	count = 0
	regression_results = []
	descriptive_results = []

	for model_name, model_id in MODELS.items():
		df_standard = pd.read_csv(f"data/results_{model_name}_standard.csv")
		df_region = pd.read_csv(f"data/results_{model_name}_region.csv")
		df = pd.concat([df_standard, df_region], axis=0, ignore_index=True)

		for outcome in OUTCOMES:
			formula = f"{outcome} ~ C(CV_framing) * C(Seniority_level)"
			model = smf.ols(
				formula=formula,
				data=df
			).fit()
			count += 1
			test_metadata = {
				"Analysis_Step": "Step_2a",
				"Model_Provider": model_name,
				"Model_Name": model_id,
				"Outcome": outcome,
				"Prompt_Version": "pooled",
				"Formula": formula
			}
			regression_info = {
				**test_metadata,
				"N": int(model.nobs),
				"Df_Model": model.df_model,
				"Df_Residual": model.df_resid,
				"R_Squared": model.rsquared,
				"Adjusted_R_Squared": model.rsquared_adj,
				"F_Statistic": model.fvalue,
				"F_P_Value": model.f_pvalue,
				"AIC": model.aic,
				"BIC": model.bic,
				"Log_Likelihood": model.llf
			}

			coefficients = model.params
			standard_errors = model.bse
			t_values = model.tvalues
			p_values = model.pvalues
			confidence_intervals = model.conf_int()

			for term in coefficients.index:
				regression_results.append({
					**regression_info,
					"Term": term,
					"Coefficient": coefficients[term],
					"Std_Error": standard_errors[term],
					"T_statistic": t_values[term],
					"P_Value": p_values[term],
					"CI_Lower": confidence_intervals.loc[term, 0],
					"CI_Upper": confidence_intervals.loc[term, 1]
				})

			grouped = (
				df.groupby(["CV_framing", "Seniority_level"])[outcome]
				.agg(
					N="count",
					Mean="mean",
					Std="std",
					Median="median"
				).reset_index()
			)

			for _,row in grouped.iterrows():
				descriptive_results.append({
					**test_metadata,
					"CV_framing": row["CV_framing"],
					"Seniority_level": row["Seniority_level"],
					"Mean": row ["Mean"],
					"Std": row["Std"],
					"Median": row["Median"]
				})

	regression_df = pd.DataFrame(regression_results)
	descriptive_df = pd.DataFrame(descriptive_results)
	print(regression_df.shape)
	print(descriptive_df.shape)

	outputdir = base_dir / "outputs" / "step_2a_interaction_effect"
	if not outputdir.exists():
		outputdir.mkdir(parents=True, exist_ok=True)

	regression_df.to_csv(outputdir/"step_2a_regression_results.csv", index=False)
	descriptive_df.to_csv(outputdir/"step_2a_descriptive_results.csv", index=False)

	print("-----------------------------------------------------------------------")
	print(f"number of interaction tests run: {count}")
	print(f"Regression result rows: {len(regression_df)}")
	print(f"Descriptive result rows: {len(descriptive_df)}")
	print("-----------------------------------------------------------------------")

	print(f"Saved: {outputdir/'step_2a_regression_results.csv'}")
	print(f"Saved: {outputdir/'step_2a_descriptive_results.csv'}")

	create_step2a_summary(outputdir)
	create_step2a_plots(outputdir)

if __name__ == "__main__":
    main()

